export const UPDATE_THEME_SELECTION = 'UPDATE_THEME_SELECTION';
export const ADD_PLAYER = 'ADD_PLAYER';
export const DELETE_PLAYER = 'DELETE_PLAYER';
export const MAKE_PLAYER_ACTIVE = 'MAKE_PLAYER_ACTIVE';
